
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: Ashu@855496
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: url_shortener_development

test:
  <<: *default
  database: url_shortener_test


production:
  <<: *default
  database: url_shortener_producation
  username: url_shortener
  password: <%= ENV['TASK_MANAGMENT_APPLICATION_DATABASE_PASSWORD'] %>







